vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images/history_content
            upload_destination: '%kernel.project_dir%/public/images/history_content'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
